# Generated by Django 4.0.4 on 2022-08-09 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('type', 'user')},
        ),
        migrations.RemoveField(
            model_name='application',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_diet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tshirt_size',
        ),
        migrations.RemoveField(
            model_name='application',
            name='under_age',
        ),
    ]
