# Generated by Django 4.0.4 on 2022-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_applicationtypeconfig_auto_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtypeconfig',
            name='auto_confirm',
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='review',
            field=models.BooleanField(default=True),
        ),
    ]
