# Generated by Django 4.0.4 on 2022-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_applicationtypeconfig_auto_confirm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_review_application', 'Can review application'), ('can_invite_application', 'Can invite application'), ('can_review_dubious_application', 'Can review dubious application'))},
        ),
    ]
