# Generated by Django 4.0.4 on 2022-08-16 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
