# Generated by Django 4.0.4 on 2022-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_review_application', 'Can review application'), ('can_invite_application', 'Can invite application'), ('can_review_dubious_application', 'Can review dubious application'), ('can_review_blocked_application', 'Can review blocked application'))},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blocked'), ('NC', 'Needs change')], default='P', max_length=2),
        ),
    ]
