# Generated by Django 4.0.4 on 2022-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_options_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtypeconfig',
            name='needs_confirmation',
        ),
        migrations.RemoveField(
            model_name='applicationtypeconfig',
            name='review',
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='auto_blocklist',
            field=models.BooleanField(default=True, help_text='Applications pass test of blocklist table on apply'),
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Applications set on status confirmed by default'),
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='dubious',
            field=models.BooleanField(default=True, help_text='Dubious reviewing system'),
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='vote',
            field=models.BooleanField(default=True, help_text='Activate voting system'),
        ),
    ]
