# Generated by Django 4.0.4 on 2022-08-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_auto_blocklist_applicationtypeconfig_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='compatible_with_others',
            field=models.BooleanField(default=False, help_text='User can confirm in more than one type'),
        ),
    ]
