# Generated by Django 4.0.4 on 2022-09-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_review_application', 'Can review application'), ('can_invite_application', 'Can invite application'), ('can_review_dubious_application', 'Can review dubious application'), ('can_review_blocked_application', 'Can review blocked application'))},
        ),
    ]
