# Generated by Django 4.0.4 on 2022-09-01 09:12

import application.models
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Edition = apps.get_model('application', 'Edition')
    Edition(name='Hack').save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=application.models.get_new_order, unique=True)),
            ],
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
        migrations.AddField(
            model_name='application',
            name='edition',
            field=models.ForeignKey(default=application.models.Edition.get_default_edition, on_delete=django.db.models.deletion.RESTRICT, to='application.edition'),
        ),
    ]
