# Generated by Django 4.0.4 on 2022-09-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_application_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='qr_code',
        ),
    ]
