# Generated by Django 4.0.7 on 2022-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_application_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtypeconfig',
            name='group',
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='file_review_fields',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
