# Generated by Django 4.0.7 on 2022-09-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_applicationtypeconfig_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_review_application', 'Can review application'), ('can_invite_application', 'Can invite application'), ('can_review_dubious_application', 'Can review dubious application'), ('can_review_blocked_application', 'Can review blocked application'), ('can_review_files', 'Can review files'))},
        ),
    ]
