# Generated by Django 4.0.7 on 2022-09-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_remove_promotionalcode_application_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='promotional_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.promotionalcode'),
        ),
    ]
