# Generated by Django 4.0.7 on 2022-10-03 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_application_promotional_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtypeconfig',
            name='public',
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='create_user',
            field=models.BooleanField(default=False, help_text='Setting this to True creates a user if it was not authenticated create a user for him to enter later'),
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='only_unauthenticated',
            field=models.BooleanField(default=False, help_text='Setting this to True, user in request will not be user on apply'),
        ),
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
