# Generated by Django 4.0.7 on 2022-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_remove_applicationtypeconfig_only_unauthenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Setting this to True doesn't show the application to registered users"),
        ),
    ]
