# Generated by Django 4.0.8 on 2022-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_applicationtypeconfig_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='expire_invitations',
            field=models.IntegerField(default=0, help_text='Setting this to different to 0, sets the days that the invitation will last until expires. 1 day before it expires there will be a reminder'),
        ),
        migrations.AlterField(
            model_name='applicationtypeconfig',
            name='file_review_fields',
            field=models.CharField(blank=True, help_text='Activate the file fields from the form that you want to review', max_length=200),
        ),
    ]
