# Generated by Django 4.0.8 on 2022-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_applicationtypeconfig_expire_invitations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtypeconfig',
            name='spots',
            field=models.PositiveIntegerField(default=100, help_text='Number of total spots for this type of participants'),
        ),
    ]
