# Generated by Django 4.0.8 on 2023-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_draftapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtypeconfig',
            name='spots',
            field=models.PositiveIntegerField(default=100, help_text='Number of total spots for this type of participants. Attrition rate will be added automatically.'),
        ),
    ]
