# Generated by Django 4.2.2 on 2023-09-11 12:05

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0031_alter_applicationtypeconfig_spots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Missing document'), ('D', 'Not accepted'), ('U', 'On review'), ('A', 'Accepted')], default='N', max_length=2)),
                ('file', models.FileField(null=True, upload_to=application.models.get_permission_slip_file_name)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.edition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_review_permission_slip', 'Can review permission slip'),),
            },
        ),
    ]
