HACKATHON_NAME = 'HackUPC'
HACKATHON_DESCRIPTION = 'Join us for BarcelonaTech\'s hackathon. 36h. 29th April - 1st May.'
HACKATHON_ORG = 'Hackers@UPC'
HACKATHON_CONTACT_EMAIL = ''
HACKATHON_SOCIALS = [('fa-facebook', 'fa-facebook')]
REGEX_HACKATHON_ORGANIZER_EMAIL = '^.*@hackupc\.com$'
HACKATHON_ORGANIZER_EMAILS = []
APP_NAME = 'MyHackUPC'
APP_EMAIL = ''
