# Generated by Django 4.0.8 on 2022-12-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': (('can_checkin_meals', 'Can checkin meals'),)},
        ),
    ]
