# Generated by Django 4.0.8 on 2022-12-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
    ]
