# Generated by Django 4.0.4 on 2022-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='calculated_vote',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
