# Generated by Django 4.0.4 on 2022-08-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_blockedlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedList',
        ),
    ]
