# Generated by Django 4.0.7 on 2022-09-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_filereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filereview',
            options={},
        ),
    ]
