# Generated by Django 4.0.7 on 2022-09-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_application_options'),
        ('review', '0006_alter_filereview_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filereview',
            unique_together={('application', 'field_name')},
        ),
    ]
