# Generated by Django 4.0.10 on 2023-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_commentreaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='emoji',
            field=models.CharField(max_length=30),
        ),
    ]
