# Generated by Django 4.0.8 on 2022-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name to identify the message', max_length=100)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(help_text='Messages will be sent at minutes divisors by 5 only')),
                ('services', models.CharField(help_text='Messages will be sent to the services you select', max_length=200)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
