# Generated by Django 4.0.8 on 2023-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='services',
            field=models.CharField(blank=True, help_text='Messages will be sent to the services you select', max_length=200),
        ),
    ]
