# Generated by Django 4.0.4 on 2022-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginrequest',
            old_name='latestRequest',
            new_name='latest_request',
        ),
        migrations.AddField(
            model_name='user',
            name='email_subscribe',
            field=models.BooleanField(default=False, verbose_name='email subscribed'),
        ),
    ]
