# Generated by Django 4.0.7 on 2022-10-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_qr_code_alter_user_diet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginRequest',
        ),
    ]
