# Generated by Django 4.0.8 on 2022-11-28 22:06

from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_loginrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.validations.disposable_email], verbose_name='email address'),
        ),
    ]
